[cosmological_parameters]
omega_m = .25 .5
ombh2 = .021 .024
omnuh2 = 0. .01
h0 = .6 .7
A_s = 1.9e-9 2.5e-9
n_s = .94 .98
tau = .02 .14

w = -1.
omega_k = 0.
wa = 0.
massive_nu = 1
massless_nu = 2.046

[mor_parameters]
; Standard SZ
Asz = 1. 9.
Bsz = 1.2 2.2
Csz = 0. 2.
Dsz = .01 .5
; Extended SZ
Bsz2 = 0.
Csz2 = 0.
Esz = 0.
DszM = 0.
; Standard X-ray
Ax = 3. 10.
Bx = .3 .9
Cx = -1. .5
Dx = .01 .5
dlnMg_dlnr = .4 1.8
; Extended X-ray
Ex = 0.
; Weak lensing
WLbias = -3. 3.
WLscatter = -3. 3.
HSTbias = -3. 3.
HSTscatterLSS = 2.8e13 8.4e13
MegacamBias = -3 3.
MegacamScatterLSS = 3.5e13 9.1e13
DESbias = 0.
DESscatterLSS = 0.
; Velocity dispersions
Adisp = 939.
Bdisp = 2.91
Cdisp = .33
Ddisp0 = .2
DdispN = 3.
; richness
Alambda = 70.
Blambda = 1.
Clambda = 1.
Dlambda = .2
; correlation coefficients
rhoSZWL = -1. 1.
rhoSZX = -1. 1.
rhoWLX = -1. 1.
rhoSZlambda = 0.
rhoSZdisp = 0.
rhoXdisp = 0.

[planck]
; http://wiki.cosmos.esa.int/planckpla2015/index.php/CMB_spectrum_%26_Likelihood_Code
A_planck = .99 1. 1.01
