[mor_parameters]
; Weak lensing
WLscatter = 0.
HSTbias = 0.
MegacamBias = 0.
MegacamScatterLSS = 0.
DES_b_dev_1 = -3. 3.
DES_b_dev_2 = -3. 3.
DES_b_dev_m = -3. 3.
DES_s_dev = -3. 3.
DES_s_dev_m = -3. 3.
DES_m_piv = 2e14

; Standard SZ
Asz = 0. 2.
Bsz = .5 2.5
Csz = -3. 5.
Dsz = .01 .5
Bsz2 = 0.
Csz2 = 0.
Esz = 0.
DszM = 0.
SPECS_calib = .9 1.1
SZmPivot = 3e14
zeta_min = 1.
; Standard X-ray
Ax = 6.
Bx = .5 
Cx =  -.4
Dx =  0.1 
dlnMg_dlnr = 0.
Ex = 0.
XraymPivot = 3e14
; Velocity dispersions
Adisp = 939.
Bdisp = 2.91
Cdisp = .33
Ddisp0 = .2
DdispN = 3.
; optical richness
Arichness = 2.3 4.6
Brichness = .2 1.8
Crichness = -1. 1.
Drichness = .01 .5
richmPivot = 3e14
Arichness_ext = 2.3 4.6
Brichness_ext = .2 1.8
Crichness_ext = -1. 1.
Drichness_ext = .01 .5
z_DESWISE = 1.1
; correlation coefficients
rhoSZWL = -.9 .9
rhoSZrichness = -.9 .9
rhoSZdisp = 0.
rhoSZX =  0. 
rhoWLX =  0. 
rhoXdisp = 0.
rhoWLrichness = -.9 .9

[cosmological_parameters]
Omega_m = .232 .4
ombh2 = .018 .027
omnuh2 = 0. .01
h0 = .6 .8
log1e10As = 1. 4.
n_s = .84 1.1
tau = .08 
; neutrinos
nnu = 3.046
num_massive_neutrinos = 1
; extensions
omega_k = 0.
w = -1. 
wa = 0.

