[mor_parameters]
; Weak lensing
WLscatter = 0.0
HSTbias = 0.0
MegacamBias = 0.0
MegacamScatterLSS = 0.0
DES_b_dev_1 = 0.0
DES_b_dev_2 = 0.0
DES_b_dev_m = 0.0
DES_s_dev = 0.0
DES_s_dev_m = 0.0
DES_m_piv = 2e14

; Standard SZ
Asz = 1.0
Bsz = 1.5
Csz = 1.0
Dsz = 0.2
Bsz2 = 0.0
Csz2 = 0.0
Esz = 0.0
DszM = 0.0
SPECS_calib = 1.0
SZmPivot = 3e14
zeta_min = 1.
; Standard X-ray
Ax = 6.
Bx = .5 
Cx =  -.4
Dx =  0.1 
dlnMg_dlnr = 0.0
Ex = 0.0
XraymPivot = 3e14
; Velocity dispersions
Adisp = 939.
Bdisp = 2.91
Cdisp = .33
Ddisp0 = .2
DdispN = 3.
; optical richness
Arichness = 3.0
Brichness = 1.0
Crichness = 0.0
Drichness = 0.3
richmPivot = 3e14
Arichness_ext = 3.0
Brichness_ext = 1.0
Crichness_ext = 0.0
Drichness_ext = 0.3
z_DESWISE = 1.1
; correlation coefficients
rhoSZWL = 0.0
rhoSZrichness = 0.0
rhoSZdisp = 0.0
rhoSZX =  0.0
rhoWLX =  0.0 
rhoXdisp = 0.0
rhoWLrichness = 0.0

[cosmological_parameters]
Omega_m_geo = 0.33
Omega_m_growth= 0.33
ombh2 =  0.0224 
omnuh2 = 0.
h0 = 0.7
log1e10As = 3.044
n_s = .96
tau = .08 
z_i=3.0
; neutrinos
nnu = 3.046
num_massive_neutrinos = 0
; extensions
omega_k = 0.0
w = -1. 
wa = 0.0


