[mor_parameters]
; Weak lensing
WLscatter = 0.
HSTbias = 0.
MegacamBias = 0.
MegacamScatterLSS = 6.3e13
DES_b_dev_1 = 0.
DES_b_dev_2 =0. 
DES_b_dev_m = 0. 
DES_s_dev = 0. 
DES_s_dev_m = 0.
DES_m_piv = 2e14

; Standard SZ
Asz = 0. 2.
Bsz = .5 2.5
Csz = -3. 5.
Dsz = .01 .5
Bsz2 = 0.
Csz2 = 0.
Esz = 0.
DszM = 0.
SPECS_calib = .9 1.2
SZmPivot = 3e14
zeta_min = 1.
; Standard X-ray
Ax = 6.5
Bx = .57 
Cx =  -.4 
Dx =  0.12
dlnMg_dlnr = 0.
Ex = 0. 
XraymPivot = 5e14
; Velocity dispersions
Adisp = 939. 
Bdisp = 2.91
Cdisp = .33
Ddisp0 = .2
DdispN = 3.
; optical richness
Arichness = 3. 5.
Brichness = .2 1.8
Crichness = -1. 1.
Drichness = .01 .5
richmPivot = 3e14
Arichness_ext = 3 4.6
Brichness_ext = .2 1.8
Crichness_ext = -4. 4.
Drichness_ext = .01 .5
z_DESWISE = 1.1
; correlation coefficients
rhoSZWL = 0.
rhoSZrichness = 0.
rhoSZdisp = 0.
rhoSZX =  0. 
rhoWLX =  0.  
rhoXdisp = 0.
rhoWLrichness =0.

[cosmological_parameters]
Omega_m_geo = .16 .58
Omega_m_growth= .16 .58
ombh2 = .019 0.025
omnuh2 = 0.
h0 = .6 .77
log1e10As = 1. 4.
n_s = 0.96
tau = .08 
z_i=3.0
; neutrinos
nnu = 3.046
num_massive_neutrinos = 0
; extensions
omega_k = 0.
w = -1. 
wa = 0.
[supernova_params]
M = -21.0  -19.253  -17.0

