[runtime]
verbosity = debug
sampler = test

[DEFAULT]
cosmosis_std_path = ${HOME}/cosmosis-standard-library
SPT_like_path = ${HOME}/SPT_NC_with_DES_WL
SPT_data_path = ${HOME}/SPT_cluster_data
SPT_survey_fields = %(SPT_like_path)s/data/SPT_SZ_ECS_500d_survey.txt
SPTcatalogfile = %(SPT_like_path)s/data/SPT_SZ_pol_230420.fits
HSTcalibfile = %(SPT_like_path)s/data/HST-39_200_X.txt
MCMF_lambda_min = %(SPT_like_path)s/data/MCMF_lambda_min.txt
surveyCutSZmax = 60.
richness_scatter_model = lognormalGaussPoisson
doWL = T
doYx = F
doMgas = F
doveldisp = F
dorichness = T

[pipeline]
modules = consistency set_scaling pk_baccoemu compute_HMF HMF_convo abundance mass_calibration
likelihoods = mass_calibration abundance
values = params_example.ini
extra_output = cosmological_parameters/sigma_8
timing = F
debug = T

[pk_baccoemu]
file = %(SPT_like_path)s/baccoemu_powerspectrum.py
compute_sigma8 = T
z_min_max = 0. 1.9
N_z = 20

[camb]
file = %(cosmosis_std_path)s/boltzmann/camb/camb_interface.py
mode=power
lmax=2500
feedback=0
power_spectra = delta_nonu
zmin = 0.
zmax = 1.9
nz = 20

[class]
file = %(cosmosis_std_path)s/boltzmann/class/class_interface.py
zmax = 2.
mpk = T
lensing = T
save_matter_power_lin = F
save_cdm_baryon_power_lin = T

[compute_HMF]
file = %(SPT_like_path)s/compute_HMF_fit_interface.py
; Tinker08 or Bocquet16
fitting_function = Tinker08
recalc_HMF = T
save_HMF_to_disk = F
Deltacrit = 200.
z_arr = .24 1.8 157.
M_arr = 13. 16. 301.

[compute_HMF_MiraTitan]
file = %(SPT_like_path)s/compute_HMF_MiraTitan_interface.py
recalc_HMF = T
save_HMF_to_disk = F
Deltacrit = 200.
mcType = None
z_arr = 0. 2. 201.
M_arr = 13. 16. 301.

[set_scaling]
file = %(SPT_like_path)s/set_scaling_interface.py
MegacamSim = .938 .028 .214 .04
MegacamMcErr = .015
MegacamCenterErr = .03
MegacamShearErr = .032
MegacamzDistErr = .012
MegacamContamCorr = .009
Megacam_LSS = 6.3e13 7e12

[HMF_convo]
file = %(SPT_like_path)s/HMF_convo_SZrichness_interface.py
observable_pairs = SZ SZ_lambdacut_shallow SZ_lambdacut_deep
z_cl_min_max = .25 1.79
Nz = 155
NPROC = 0

[abundance]
file = %(SPT_like_path)s/abundance_interface.py
z_cl_min_max = .25 1.78
lambda_min = T
covmat = F
NPROC = 0

[mass_calibration]
file = %(SPT_like_path)s/mass_calibration_MC_interface.py
lambda_min = T
HSTfile = None
MegacamFile = None
DESfile = %(SPT_like_path)s/data/WL_data_500kpch_MCMF_230420.h5
DES_WL_priors_file = %(SPT_like_path)s/data/WLcalib_MCMF_dnf_500kpch.h5
DESboostfile = %(SPT_like_path)s/data/boost_smooth_dnf_MCMF.txt
DESboost_z_arr = 0.2 0.28 0.36 0.44 0.52 0.6 0.68 0.76 0.84 0.92 1.
DESmiscenterfile = %(SPT_like_path)s/data/miscenter_SPTopt.txt
DEScentertype = MCMF
mcType = DK15
YXPARAM = SPT_XVP
NPROC = 0
z_cl_min_max = .25 1.78
get_stacked_DES = F

[stacked_mass]
file = %(SPT_like_path)s/stacked_mass_interface.py
z_bins = 0.25 0.48 0.69 0.95
rot_mat_row = 1.4 1.0
rot_bins_x = 1.5 2.4 3.1 6.1
rot_bins_y = 1.65 2.8 3.7
DES_WL_priors_file = %(SPT_like_path)s/data/WLcalib_MCMF_dnf_500kpch.h5

[meanmass_like]
file = %(SPT_like_path)s/meanmass_like_interface.py
meanmass_file = cov_mass.txt

[dNdzdlambda]
file = %(SPT_like_path)s/dNdzdlambda_interface.py
z_cl_min_max = .25 1.78
NPROC = 0

[consistency]
file = %(cosmosis_std_path)s/utility/consistency/consistency_interface.py

[sigma8_rescale]
file = %(cosmosis_std_path)s/utility/sample_sigma8/sigma8_rescale.py

