[runtime]
sampler = multinest

[multinest]
live_points = 500
efficiency = .3
max_iterations = 10000
multinest_outfile_root = multinest_

[output]
filename = multinest.txt
format = text

[DEFAULT]
SPTdatafile = ${COSMOSIS_SRC_DIR}/modules/cosmosis_spt_cluster/SPTcluster_data.py
SPTcatalogfile = ${COSMOSIS_SRC_DIR}/modules/cosmosis_spt_cluster/data/SPT2500d.fits

[pipeline]
modules = consistency camb planck compute_HMF abundance mass_calibration
likelihoods = planck2015 abundance mass_calibration
values = params_LCDM_SZWLYx_Planck.ini
priors = ${COSMOSIS_SRC_DIR}/modules/cosmosis_spt_cluster/planck_prior.ini ${COSMOSIS_SRC_DIR}/modules/cosmosis_spt_cluster/WL_priors.ini
extra_output = cosmological_parameters/sigma_8

[planck]
file = cosmosis-standard-library/likelihood/planck2015/planck_interface.so
data_1 = /homes/sbocquet/Planck15/Data/plc_2.0/hi_l/plik_lite/plik_lite_v18_TT.clik
data_2 = /homes/sbocquet/Planck15/Data/plc_2.0/low_l/bflike/lowl_SMW_70_dx11d_2014_10_03_v5c_Ap.clik

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2650
feedback=0
do_tensors=F
do_lensing=T
do_nonlinear=F
high_ell_template=${COSMOSIS_SRC_DIR}/cosmosis-standard-library/boltzmann/camb/camb_Jan15/HighLExtrapTemplate_lenspotentialCls.dat
; because we will be using the Planck likelihood we also need to set the
; accuracy to higher values. This makes a big difference to the likelihood values (delta log L ~ 36)
accuracy_boost=1.1  ;CAMB accuracy boost parameter
high_accuracy_default=T
zmin = 0.
zmax = 2.
nz = 21

[compute_HMF]
file = modules/cosmosis_spt_cluster/compute_HMF_interface.py
recalc_HMF = T
save_HMF_to_disk = F
Deltacrit = 500.

[abundance]
file = modules/cosmosis_spt_cluster/abundance_interface.py
SZmPivot = 3e14
surveyCutSZ = 5. 47.
surveyCutRedshift = .25 2.
NPROC = 2

[mass_calibration]
file = modules/cosmosis_spt_cluster/mass_calibration_interface.py
WLsimcalibfile = ${COSMOSIS_SRC_DIR}/modules/cosmosis_spt_cluster/WLsimcalib_data.py
doWL = T
doYx = T
doMgas = F
doveldisp = F
dorichness = F
HSTfile = ${COSMOSIS_SRC_DIR}/modules/cosmosis_spt_cluster/data/hst_20160930_xray.pkl
MegacamDir = ${COSMOSIS_SRC_DIR}/modules/cosmosis_spt_cluster/data/Megacam
DESDir = None
SZmPivot = 3e14
XraymPivot = 5e14
richmPivot = 3e14
YXPARAM = SPT_XVP
mcType = DK15
NPROC = 4
surveyCutSZ = 5. 47.
surveyCutRedshift = .25 2.

[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py
