[runtime]
sampler = test

[DEFAULT]
cosmosis_std_path = ${HOME}/cosmosis-standard-library
SPT_like_path = ${HOME}/SPT_NC_with_DES_WL
SPT_data_path = ${HOME}/SPT_cluster_data
DES_lensing_path = /archive1/users/bocquet/DESY3
SPT_survey_fields = %(SPT_data_path)s/SPT_SZ_ECS_500d_survey_210529_mix.txt
SPTcatalogfile = %(SPT_data_path)s/SPT_meta_v3_cut.fits
SPT_doublecounts = %(SPT_data_path)s/SPT_doublecounts.py
WLsimcalibfile = %(SPT_data_path)s/WLsimcalib_data_Megacam.py
HSTcalibfile = %(SPT_data_path)s/HST-39_200_X.txt
MCMF_lambda_min = %(SPT_data_path)s/MCMF_lambda_min.txt
surveyCutSZmax = 60.
observable_pairs = SZ_lambdacut_shallow SZ_lambdacut_deep richness_SZ
pairs_zmin = .25 .25 .25
pairs_zmax = 1.78 1.78 1.78
pairs_Nz = 154 154 154
richness_scatter_model = lognormal

[pipeline]
modules = consistency DES_WL_prior set_scaling camb compute_HMF mass_calibration HMF_convo abundance dNdzdlambda
likelihoods = DES_WL_prior mass_calibration abundance
values = params_example.ini
extra_output = cosmological_parameters/sigma_8 dN/dN_dz_0 dN/dN_dz_1 dN/dN_dz_2 dN/dN_dz_3 dN/dN_dz_4 dN/dN_dz_5 dN/dN_dz_6 dN/dN_dz_7 dN/dN_dz_8 dN/dN_dz_9 dN/dN_dz_10 dN/dN_dz_11 dN/dN_dz_12 dN/dN_dz_13 dN/dN_dz_14 dN/dN_dz_15 dN/dN_dxi_0 dN/dN_dxi_1 dN/dN_dxi_2 dN/dN_dxi_3 dN/dN_dxi_4 dN/dN_dxi_5 dN/dN_dxi_6 dN/dN_dxi_7 dN/dN_dxi_8 dN/dN_dxi_9 dN/dN_dxi_10 dN/dN_dlambda_0 dN/dN_dlambda_1 dN/dN_dlambda_2 dN/dN_dlambda_3 dN/dN_dlambda_4 dN/dN_dlambda_5 dN/dN_dlambda_6 dN/dN_dlambda_7 dN/dN_dlambda_8 dN/dN_dlambda_9 dN/dN_dlambda_10 dN/dN_dlambda_11 dN/dN_dlambda_12 dN/dN_dlambda_13 dN/dN_dlambda_14 DES_stack/shear_zloxilo_0 DES_stack/shear_zloxilo_1 DES_stack/shear_zloxilo_2 DES_stack/shear_zloxilo_3 DES_stack/shear_zloxilo_4 DES_stack/shear_zloxilo_5 DES_stack/shear_zloxilo_6 DES_stack/shear_zloxilo_7 DES_stack/shear_zloxihi_0 DES_stack/shear_zloxihi_1 DES_stack/shear_zloxihi_2 DES_stack/shear_zloxihi_3 DES_stack/shear_zloxihi_4 DES_stack/shear_zloxihi_5 DES_stack/shear_zloxihi_6 DES_stack/shear_zloxihi_7 DES_stack/shear_zhixilo_0 DES_stack/shear_zhixilo_1 DES_stack/shear_zhixilo_2 DES_stack/shear_zhixilo_3 DES_stack/shear_zhixilo_4 DES_stack/shear_zhixilo_5 DES_stack/shear_zhixilo_6 DES_stack/shear_zhixihi_0 DES_stack/shear_zhixihi_1 DES_stack/shear_zhixihi_2 DES_stack/shear_zhixihi_3 DES_stack/shear_zhixihi_4 DES_stack/shear_zhixihi_5 DES_stack/shear_zhixihi_6 DES_stack/DeltaSigma_zloxilo_0 DES_stack/DeltaSigma_zloxilo_1 DES_stack/DeltaSigma_zloxilo_2 DES_stack/DeltaSigma_zloxilo_3 DES_stack/DeltaSigma_zloxilo_4 DES_stack/DeltaSigma_zloxilo_5 DES_stack/DeltaSigma_zloxilo_6 DES_stack/DeltaSigma_zloxilo_7 DES_stack/DeltaSigma_zloxihi_0 DES_stack/DeltaSigma_zloxihi_1 DES_stack/DeltaSigma_zloxihi_2 DES_stack/DeltaSigma_zloxihi_3 DES_stack/DeltaSigma_zloxihi_4 DES_stack/DeltaSigma_zloxihi_5 DES_stack/DeltaSigma_zloxihi_6 DES_stack/DeltaSigma_zloxihi_7 DES_stack/DeltaSigma_zhixilo_0 DES_stack/DeltaSigma_zhixilo_1 DES_stack/DeltaSigma_zhixilo_2 DES_stack/DeltaSigma_zhixilo_3 DES_stack/DeltaSigma_zhixilo_4 DES_stack/DeltaSigma_zhixilo_5 DES_stack/DeltaSigma_zhixilo_6 DES_stack/DeltaSigma_zhixihi_0 DES_stack/DeltaSigma_zhixihi_1 DES_stack/DeltaSigma_zhixihi_2 DES_stack/DeltaSigma_zhixihi_3 DES_stack/DeltaSigma_zhixihi_4 DES_stack/DeltaSigma_zhixihi_5 DES_stack/DeltaSigma_zhixihi_6 DES_stack/DeltaSigma_data_zloxilo_0 DES_stack/DeltaSigma_data_zloxilo_1 DES_stack/DeltaSigma_data_zloxilo_2 DES_stack/DeltaSigma_data_zloxilo_3 DES_stack/DeltaSigma_data_zloxilo_4 DES_stack/DeltaSigma_data_zloxilo_5 DES_stack/DeltaSigma_data_zloxilo_6 DES_stack/DeltaSigma_data_zloxilo_7 DES_stack/DeltaSigma_data_zloxihi_0 DES_stack/DeltaSigma_data_zloxihi_1 DES_stack/DeltaSigma_data_zloxihi_2 DES_stack/DeltaSigma_data_zloxihi_3 DES_stack/DeltaSigma_data_zloxihi_4 DES_stack/DeltaSigma_data_zloxihi_5 DES_stack/DeltaSigma_data_zloxihi_6 DES_stack/DeltaSigma_data_zloxihi_7 DES_stack/DeltaSigma_data_zhixilo_0 DES_stack/DeltaSigma_data_zhixilo_1 DES_stack/DeltaSigma_data_zhixilo_2 DES_stack/DeltaSigma_data_zhixilo_3 DES_stack/DeltaSigma_data_zhixilo_4 DES_stack/DeltaSigma_data_zhixilo_5 DES_stack/DeltaSigma_data_zhixilo_6 DES_stack/DeltaSigma_data_zhixihi_0 DES_stack/DeltaSigma_data_zhixihi_1 DES_stack/DeltaSigma_data_zhixihi_2 DES_stack/DeltaSigma_data_zhixihi_3 DES_stack/DeltaSigma_data_zhixihi_4 DES_stack/DeltaSigma_data_zhixihi_5 DES_stack/DeltaSigma_data_zhixihi_6
timing = F
debug = T
quiet = T

[DES_WL_prior]
file =  %(SPT_like_path)s/DES_WL_prior_interface.py
DES_WL_priors_file = /archive2/users/grandis/DES-Y3-SPT/SZ-dnf/_18-25_metapost_

[p_k_baccoemu]
file = %(SPT_like_path)s/baccoemu_powerspectrum.py
z_min_max = 0. 2.
N_z = 21

[camb]
file = %(cosmosis_std_path)s/boltzmann/camb/camb_interface.py
mode=all
lmax=2500
feedback=0
power_spectra = delta_nonu
zmin = 0.
zmax = 2.
nz = 21

[compute_HMF]
file = %(SPT_like_path)s/compute_HMF_fit_interface.py
; Tinker08 or Bocquet16
fitting_function = Tinker08
recalc_HMF = T
save_HMF_to_disk = F
Deltacrit = 200.

[compute_HMF_MiraTitan]
file = %(SPT_like_path)s/compute_HMF_MiraTitan_interface.py
recalc_HMF = T
save_HMF_to_disk = F
Deltacrit = 200.
mcType = None
z_arr = 0. 2. 21.
M_arr = 13. 16. 301.

[set_scaling]
file = %(SPT_like_path)s/set_scaling_interface.py

[HMF_convo]
file = %(SPT_like_path)s/HMF_convo_interface.py
NPROC = 0

[abundance]
file = %(SPT_like_path)s/abundance_interface.py
surveyCutRedshift = .25 1.78
lambda_min = T
covmat = F
NPROC = 0

[mass_calibration]
file = %(SPT_like_path)s/mass_calibration_MC_interface.py
lambda_min = T
doWL = T
doYx = F
doMgas = F
doveldisp = F
dorichness = T
HSTfile = None
MegacamFile = None
DESfile = %(DES_lensing_path)s/WL_data_500kpch_1h_SPT.h5
DESboostfile = %(DES_lensing_path)s/WL_model/boost_smooth_dnf_SZ.txt
DESmiscenterfile = %(DES_lensing_path)s/WL_model/miscenter_3obs_mask_211020.txt
DEScentertype = SPT 
mcType = DK15
YXPARAM = SPT_XVP
NPROC = 0
surveyCutRedshift = .25 1.78
get_stacked_DES = F

[dNdzdlambda]
file = %(SPT_like_path)s/dNdzdlambda_interface.py
surveyCutRedshift = .25 1.78
NPROC = 0

[consistency]
file = %(cosmosis_std_path)s/utility/consistency/consistency_interface.py

[sigma8_rescale]
file = %(cosmosis_std_path)s/utility/sample_sigma8/sigma8_rescale.py

