[cosmological_parameters]
omega_m = .05 0.3 .6
h0 = .6 0.72 .85
ombh2 = .02 0.022 .024
n_s = .94 0.96 .97
A_s = 1e-9 1.7e-9 3e-9
omega_k = 0.0
w = -1.0
wa = 0.0
tau = 0.08

[mor_parameters]
; Standard SZ
Asz = 1 4. 10
Bsz = 1. 1.6 2.5
Csz = -1. 0.5 .5
Dsz = .01 0.2 .5
; Extended SZ
Bsz2 = 0.
Csz2 = 0.
Esz = 0.
DszM = 0.
; Standard X-ray
Ax = 3. 6. 10.
Bx = .3 .5 .7
Cx = -1. -.4 .5
Dx = .01 0.1 .5
slope_MgR = 1.16
; Extended X-ray
Ex = 0.
; Weak lensing
WLbias = -3. 0. 3.
WLscatter = -3. 0. 3.
HSTbias = -3. 0. 3.
HSTscatterLSS = 2.8e13 6e13 8.4e13
MegacamBias = -3 0. 3.
MegacamScatterLSS = 3.5e13 6e13 9.1e13
DESbias = -3. 0. 3.
; Velocity dispersions
Adisp = 939.
Bdisp = 2.91
Cdisp = .33
Ddisp0 = .2
DdispN = 3.
; richness
Alambda = 70.
Blambda = 1.
Clambda = 1.
Dlambda = .2
; correlation coefficients
rhoSZlambda = 0.
rhoSZdisp = 0.
rhoSZX = -1. 0. 1.
rhoSZWL = -1. 0. 1.
rhoWLX = -1. 0. 1.
rhoXdisp = 0.
