[cosmological_parameters]
omega_m = 0.3
h0 = 0.72
ombh2 = 0.022
n_s = 0.96
A_s = 1.7e-9
omega_k = 0.0
w = -1.0
wa = 0.0
tau = 0.08

[mor_parameters]
; Standard SZ
Asz = 4.
Bsz = 1.6
Csz = 0.5
Dsz = 0.2
; Extended SZ
Bsz2 = 0.
Csz2 = 0.
Esz = 0.
DszM = 0.
; Standard X-ray
Ax = 6.
Bx = .5
Cx = -.4
Dx = 0.1
slope_MgR = 1.16
; Extended X-ray
Ex = 0.
; Weak lensing
WLbias = 0.
WLscatter = 0.
HSTbias = 0.
HSTscatterLSS = 6e13
MegacamBias = 0.
MegacamScatterLSS = 6e13
DESbias = 0.
DESscatterLSS = 6e13
; Velocity dispersions
Adisp = 939.
Bdisp = 2.91
Cdisp = .33
Ddisp0 = .2
DdispN = 3.
; richness
Alambda = 70.
Blambda = 1.
Clambda = 1.
Dlambda = .2
; correlation coefficients
rhoSZlambda = 0.
rhoSZdisp = 0.
rhoSZX = 0.
rhoSZWL = 0.
rhoWLX = 0.
rhoXdisp = 0.
